name: build and push deletetask

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read      

jobs:
  build-tag-push:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: acb3d991-a6f1-4d2a-adae-cf23331bcdfa
          tenant-id: ce2f68bd-57d5-44f2-ab38-0c7ced51b46b
          subscription-id: 30795018-f759-40ff-9c87-7d73f6cc4d87

      - name: Image Build
        run: docker build -t deletetasktodo:v1 .

      - name: ACR login
        run: az acr login --name manoclusterregistry

      - name: Image Tag
        run: docker tag deletetasktodo:v1 manoclusterregistry.azurecr.io/deletetasktodo:v1
        
      - name: ACR Push
        run: docker push manoclusterregistry.azurecr.io/deletetasktodo:v1
      

  
